# Generated by Django 2.2.17 on 2021-01-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0015_add_unique_together_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentitlement',
            name='order_number',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourseentitlement',
            name='order_number',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
